project:
  type: website
  output-dir: .
  render:
    - index.qmd
    - about_me.qmd
    - Resume.qmd
    - My_Plants.qmd
    - CV.qmd

format:
  html:
    theme:
      light: Flatly
    css: styles.css

    include-in-header:
      text: |
        <!-- Load Bootstrap Icons -->
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">

    include-after-body:
      text: |
        <script src="js/folder-sync.js"></script>
        <script src="js/sidebar-state.js"></script>

    grid:
      sidebar-width: 250px
      body-width: 2000px
      margin-width: 200px
      gutter-width: 1rem

website:
  title: "Nolan Kurtz"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    pinned: true
    border: false
    background: "#FFFFFF"
    foreground: "#000000"
    link-color: "#FFFFFF"
    contents:
      - text: Home
        icon: house
        href: index.qmd

      - section: "My Info"
        icon: folder
        contents:
          - text: About Me
            href: about_me.qmd
          - text: Resume
            href: Resume.qmd
          - text: CV
            href: CV.qmd

      - section: "Horticulture"
        icon: folder
        contents:
          - text: My Plants
            href: My_Plants.qmd

  page-footer:
    left: |
      <a href="https://www.maryam-nouriaiin.com/" target="_blank">
        <i class="bi bi-link"></i> Website
      </a><br>
      <a href="https://github.com/Maryam-NouriAiin/website_template" target="_blank">
        Template by Maryam Nouri-Aiin
      </a>
